<?php
/**
 * @file
 */

include_once('humanitarianresponse_organizations.features.inc');

/**
 * Implements hook_cron()
 */
function humanitarianresponse_organizations_cron() {
  humanitarianresponse_core_feeds_check('csv_organization_types', 'http://terms.humanitarianresponse.info/organization-types.csv');
  humanitarianresponse_core_feeds_check('csv_organizations', 'http://terms.humanitarianresponse.info/organizations.csv');
}
